/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import static Pantallas.EmpleadosP.txtDni;
import com.placeholder.PlaceHolder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import metodos.conectar;

/**
 *
 * @author Karenrgast
 */
public class DepartamentoP extends javax.swing.JFrame {

    /**
     * Creates new form DepartamentoP
     */
    public DepartamentoP() {
        initComponents();
        this.setLocationRelativeTo(null); 
        conectar.Conectar();
        ArrayList<String> lista= new ArrayList<String>();
        
        lista=conectar.llenar_comboLocaliza();
        for(int i=0; i<lista.size(); i++){
        CmbLocali.addItem(lista.get(i));
        }
        
        txtNombreD.setEnabled(false);
        txtNombreDirec.setEnabled(false);
        txtFechaIngreso.setEnabled(false);
        CmbLocali.setEnabled(false);
        BtnGuardar.setVisible(false);
        BtnEliminar.setVisible(false);
        BtnModificar.setEnabled(false);
        BtnGuardar2.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDno = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombreDirec = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaIngreso = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CmbLocali = new javax.swing.JComboBox<>();
        BtnGuardar2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Departamento");

        jLabel2.setText("Nombre de Departamento");

        jLabel3.setText("Numero de Departamento ");

        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/buscar.png"))); // NOI18N
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Super Dni");

        jLabel5.setText("Fecha de Ingreso del Director");

        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Agregar.png"))); // NOI18N
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/modificar.png"))); // NOI18N
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/eliminar.png"))); // NOI18N
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("Localización");

        BtnGuardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/guardar.png"))); // NOI18N
        BtnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardar2ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/back_arrow_14447.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnGuardar2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CmbLocali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtNombreDirec))
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDno, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnEliminar)))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnBuscar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CmbLocali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnGuardar)
                            .addComponent(BtnModificar)
                            .addComponent(BtnEliminar)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        Connection link;
        
        try {
            link = DriverManager.getConnection("jdbc:mysql://localhost/DB41", "root", "12503970");
            Statement comando = link.createStatement();
            conectar c=new conectar();
            String dato;
            dato=this.txtDno.getText();
            
            ResultSet rs=comando.executeQuery("SELECT NombreDpto, Fechaingreso, DniDirector, localizaciones_dpto.UbicacionDpto "
                    + "FROM departamento "
                    + "INNER JOIN localizaciones_dpto ON localizaciones_dpto.NumeroDpto=departamento.NumeroDpto "
                    + "WHERE departamento.NumeroDpto='"+dato+"';");
            
            if(rs.next()){
                
            txtNombreD.setText(rs.getString(1));
            txtNombreDirec.setText(rs.getString(3));
            txtFechaIngreso.setText(rs.getString(2));
            CmbLocali.setSelectedItem(rs.getString(4));
            
            txtNombreD.setEnabled(true);
            txtNombreDirec.setEnabled(true);
            txtFechaIngreso.setEnabled(true);
            CmbLocali.setEnabled(true);
            BtnBuscar.setEnabled(false);
            BtnModificar.setEnabled(true);
            
            txtDno.setEnabled(false);
            
            txtNombreD.setEditable(false);
            txtNombreDirec.setEditable(false);
            txtFechaIngreso.setEditable(false);
            CmbLocali.setEditable(false);
        
           
            }else {
                JOptionPane.showMessageDialog(rootPane, "No se ha encontrado ningún departamento con ése número ");
                int r=JOptionPane.showConfirmDialog(rootPane, "Desea agregar un nuevo departamento?");
                
                
                if(r==0){
                    PlaceHolder holder = new PlaceHolder(txtFechaIngreso, "1998-08-25");
                    BtnGuardar.setVisible(true);
                    txtNombreD.setEnabled(true);
                    txtNombreDirec.setEnabled(true);
                    txtFechaIngreso.setEnabled(true);
                    CmbLocali.setEnabled(true);
                    
                    
                     }
            }
            
            
        }
         catch (SQLException ex) {
            setTitle(ex.toString());
            
        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
            
            txtNombreD.setEditable(true);
            txtNombreDirec.setEditable(true);
            txtFechaIngreso.setEditable(true);
            CmbLocali.setEditable(true);
            txtDno.setEnabled(false);
            BtnGuardar.setVisible(false);
            BtnModificar.setVisible(false);
            BtnEliminar.setVisible(true);
            BtnGuardar2.setVisible(true);
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
        
        try{
        Connection link=DriverManager.getConnection("jdbc:mysql://localhost/DB41", "root", "12503970");
        Statement comando = link.createStatement();
        String dato3, dato1, dato2;
        dato1=(String) CmbLocali.getSelectedItem();
        dato3=this.txtDno.getText();
        comando.executeUpdate("INSERT INTO departamento VALUES("+txtDno.getText()+ ",'"+txtNombreD.getText()+"', '"+txtNombreDirec.getText()+"', '"+txtFechaIngreso.getText()+"');");
        JOptionPane.showMessageDialog(null, "Departamento agregado exitosamente "
                    , "Mensaje de bienvenida",
                    JOptionPane.INFORMATION_MESSAGE);
       txtDno.setText(null);
       txtDno.setEnabled(true);
       txtDno.setEditable(true);
       txtNombreD.setText(null);
       txtNombreD.setEnabled(false);
       txtNombreDirec.setEnabled(false);
       txtNombreDirec.setText(null);
       txtFechaIngreso.setText(null);
       CmbLocali.setEnabled(false);
       txtFechaIngreso.setEnabled(false);
       BtnBuscar.setEnabled(true);
       BtnGuardar.setVisible(false);
       BtnEliminar.setVisible(false);
               
    }catch(SQLException ex){
        setTitle(ex.toString());
        JOptionPane.showMessageDialog(null, "No se pudo agregar el Departamento "
                    , "Mensaje de error",
                    JOptionPane.ERROR);
    }
    }                                          

    private void RdBtnSubMujerActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    

    
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
        try{
        Connection link=DriverManager.getConnection("jdbc:mysql://localhost/DB41", "root", "12503970");
        Statement comando = link.createStatement();
        String dato3;
        dato3=this.txtDno.getText();
        int r=JOptionPane.showConfirmDialog(rootPane, "Desea eliminar el registro?");
        if(r==0){
        comando.executeUpdate("DELETE * FROM departament WHERE NumeroDpto='"+dato3+"';");
        JOptionPane.showMessageDialog(rootPane, "Se ha eliminado correctamente");
       txtDno.setText(null);
       txtDno.setEnabled(true);
       txtDno.setEditable(true);
       txtNombreD.setText(null);
       txtNombreDirec.setText(null);
       txtFechaIngreso.setText(null);
       txtNombreD.setEnabled(false);
        txtNombreDirec.setEnabled(false);
        txtFechaIngreso.setEnabled(false);
        CmbLocali.setEnabled(false);

       
        }
       
    }catch(SQLException ex){
        setTitle(ex.toString());
        
    }
        
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardar2ActionPerformed
        // TODO add your handling code here:
        try{
        Connection link=DriverManager.getConnection("jdbc:mysql://localhost/DB41", "root", "12503970");
        Statement comando = link.createStatement();
        String dato3, dato1, dato2;
        dato1=(String) CmbLocali.getSelectedItem();
        dato3=this.txtDno.getText();
        comando.executeUpdate("UPDATE departamento SET NumeroDpto="+txtDno.getText()+ ", NombreDpto='"+txtNombreD.getText()+"', DniDirector='"+txtNombreDirec.getText()+"', Fechaingreso='"+txtFechaIngreso.getText()+"' WHERE NumeroDpto='"+dato3+"';");
        JOptionPane.showMessageDialog(null, "Departamento modificado exitosamente "
                    , "Mensaje de bienvenida",
                    JOptionPane.INFORMATION_MESSAGE);
       txtDno.setText(null);
       txtDno.setEnabled(true);
       txtDno.setEditable(true);
       txtNombreD.setText(null);
       txtNombreD.setEnabled(false);
       txtNombreDirec.setEnabled(false);
       txtNombreDirec.setText(null);
       txtFechaIngreso.setText(null);
       CmbLocali.setEnabled(false);
       txtFechaIngreso.setEnabled(false);
       BtnBuscar.setEnabled(true);
       BtnGuardar.setVisible(false);
       BtnEliminar.setVisible(false);
               
    }catch(SQLException ex){
        setTitle(ex.toString());
        
    }
    }//GEN-LAST:event_BtnGuardar2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int r=JOptionPane.showConfirmDialog(rootPane, "Desea salir?");
                if(r==0){ 
        Inicio p =new Inicio();
        p.setVisible(true);
        this.setVisible(false);
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartamentoP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartamentoP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartamentoP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartamentoP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
          
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartamentoP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnGuardar2;
    private javax.swing.JButton BtnModificar;
    public static javax.swing.JComboBox<String> CmbLocali;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDno;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtNombreD;
    private javax.swing.JTextField txtNombreDirec;
    // End of variables declaration//GEN-END:variables
}

