/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import metodos.conectar;
import javax.swing.*;

/**
 *
 * @author Karenrgast
 */
public class EmpleadosP extends javax.swing.JFrame {

    /**
     * Creates new form EmpleadosP
     */
    public EmpleadosP() {
        initComponents();
        conectar.Conectar();
         this.setLocationRelativeTo(null); 
        ArrayList<String> lista= new ArrayList<String>();
        CmbDepartamento.removeAllItems();
        txtSuperDni.setEnabled(false);
        txtNombre.setEnabled(false);
        txtApellidoP.setEnabled(false);
        txtApellidoM.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtFechaNac.setEnabled(false);
        txtSubNombre.setEnabled(false);
        txtSubFechaNac.setEnabled(false);
        RdBtnMujer.setEnabled(false);
        RdBtnHombre.setEnabled(false);
        txtSubFechaNac.setEnabled(false);
        txtSueldo.setEnabled(false);
       
        RdBtnSubMujer.setVisible(false);
        RdBtnSubHombre.setVisible(false);
        CmbDepartamento.setVisible(false);
        CmbSubRelacion.setVisible(false);
        RdBtnMujer.setVisible(false);
        RdBtnHombre.setVisible(false);
        txtSexo.setEnabled(false);
        txtSubSexo.setEnabled(false);
        txtDepartamento.setEnabled(false);
        txtSubRelacion.setEnabled(false);
        BtnModificar.setVisible(false);
        BtnAgregar.setVisible(false);
        BtnEliminar.setVisible(false);
        BtnGuardar.setVisible(false);
        
      
        
        lista=conectar.llenar_comboDepartamento();
        for(int i=0; i<lista.size(); i++){
        CmbDepartamento.addItem(lista.get(i));
       }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtApellidoM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CmbDepartamento = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        BtnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtFechaNac = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        RdBtnMujer = new javax.swing.JRadioButton();
        RdBtnHombre = new javax.swing.JRadioButton();
        BtnEliminar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtSuperDni = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSubNombre = new javax.swing.JTextField();
        RdBtnSubMujer = new javax.swing.JRadioButton();
        RdBtnSubHombre = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtSubFechaNac = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CmbSubRelacion = new javax.swing.JComboBox<>();
        txtSexo = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();
        txtSubRelacion = new javax.swing.JTextField();
        txtSubSexo = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.select"));

        jLabel10.setText("Sueldo");

        txtSueldo.setToolTipText("");

        jLabel4.setText("Apellido Materno");

        jLabel9.setText("Departamento");

        jLabel2.setText("Nombre");

        CmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Investigación", "Administración", "Sede Central" }));
        CmbDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbDepartamentoActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        BtnAgregar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        BtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Agregar.png"))); // NOI18N
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("Empleados");

        jLabel5.setText("Apellido Paterno");

        jLabel11.setText("Dni");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/buscar.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha de Nacimiento");

        txtFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacActionPerformed(evt);
            }
        });

        jLabel7.setText("Dirección");

        jLabel8.setText("Sexo");

        RdBtnMujer.setSelected(true);
        RdBtnMujer.setText("M");

        RdBtnHombre.setText("H");

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/eliminar.png"))); // NOI18N
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/modificar.png"))); // NOI18N
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        jLabel12.setText("Super Dni");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel13.setText("Subordinado");

        jLabel14.setText("Nombre");

        RdBtnSubMujer.setText("M");
        RdBtnSubMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnSubMujerActionPerformed(evt);
            }
        });

        RdBtnSubHombre.setText("H");

        jLabel15.setText("Sexo");

        jLabel16.setText("Fecha de Nacimiento");

        txtSubFechaNac.setToolTipText("");

        jLabel17.setText("Relación");
        jLabel17.setToolTipText("");

        CmbSubRelacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hijo", "Hija", "Esposo", "Esposa" }));

        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/guardar.png"))); // NOI18N
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/back_arrow_14447.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaNac)
                                    .addComponent(txtApellidoP)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(42, 42, 42)
                                .addComponent(txtApellidoM))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSubFechaNac))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSubNombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtDireccion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSubRelacion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CmbSubRelacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscar)))
                                .addGap(0, 12, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(txtSuperDni, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(CmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel8)
                        .addGap(11, 11, 11)
                        .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RdBtnMujer)
                            .addComponent(RdBtnHombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(78, 78, 78))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtSubSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RdBtnSubMujer)
                                    .addComponent(RdBtnSubHombre)
                                    .addComponent(BtnAgregar))
                                .addGap(24, 24, 24))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtSuperDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(RdBtnMujer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RdBtnHombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtSubSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtSubNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtSubFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtSubRelacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CmbSubRelacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(RdBtnSubMujer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RdBtnSubHombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // TODO add your handling code here:
        try{
        Connection link=DriverManager.getConnection("jdbc:mysql://localhost/DB41", "root", "12503970");
        Statement comando = link.createStatement();
        String dato3, dato1, dato2;
        dato1=(String) CmbSubRelacion.getSelectedItem();
        dato2=(String) CmbDepartamento.getSelectedItem();
        dato3=this.txtDni.getText();
        comando.executeUpdate("INSERT INTO empleado(Dni, Nombre, Apellido1, Apellido2, FechaNac, Direccion, Sexo, Sueldo, SuperDni) VALUES('"+txtDni.getText()+"','"+txtNombre.getText()+"','"+txtApellidoP.getText()+"','"+txtApellidoM.getText()+"','"+txtFechaNac.getText()+"','"+txtDireccion.getText()+"','"+txtSexo.getText()+"','"+txtSueldo.getText()+"','"+txtSuperDni.getText()+"');");
        JOptionPane.showMessageDialog(null, "Empleado regsitrado  exitosamente "
                    , "Mensaje de bienvenida",
                    JOptionPane.INFORMATION_MESSAGE);
       txtDni.setText(null);
       txtDni.setEnabled(true);
       txtDni.setEditable(true);
       txtNombre.setText(null);
       txtNombre.setEnabled(false);
       txtApellidoP.setEnabled(false);
       txtApellidoM.setEnabled(false);
       txtDepartamento.setEnabled(false);
       txtSueldo.setEnabled(false);
       txtSuperDni.setEnabled(false);
       txtDireccion.setEnabled(false);
       txtFechaNac.setEnabled(false);
       
       txtApellidoP.setText(null);
       txtApellidoM.setText(null);
       txtDepartamento.setText(null);
       txtSueldo.setText(null);
       txtSuperDni.setText(null);
       txtDireccion.setText(null);
       txtFechaNac.setText(null);
       txtSubNombre.setText(null);
       txtSubFechaNac.setText(null);
       txtSexo.setText(null);
       BtnAgregar.setVisible(false);
       
       
       
       
       
      
       
    }catch(SQLException ex){
        setTitle(ex.toString());
        
    }
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void RdBtnSubMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnSubMujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdBtnSubMujerActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Connection link;
        
        try {
            link = DriverManager.getConnection("jdbc:mysql://localhost/DB41", "root", "12503970");
            Statement comando = link.createStatement();
            conectar c=new conectar();
            String dato;
            dato=this.txtDni.getText();
            
            ResultSet rs=comando.executeQuery("SELECT Nombre,Apellido1,Apellido2,SuperDni,Direccion, Sueldo,empleado.Sexo, departamento.NombreDpto, subordinado.NomSubordinado, subordinado.Sexo , subordinado.FechaNac, subordinado.Relacion, empleado.FechaNac "
                    + "FROM DB41.empleado "
                    + "INNER JOIN departamento "
                    + "ON empleado.Dno=departamento.NumeroDpto INNER JOIN subordinado ON subordinado.DniEmpleado=empleado.Dni "
                    + "WHERE Dni ='"+dato+"';");
            
            if(rs.next()){
                 
            txtNombre.setText(rs.getString(1));
            txtApellidoP.setText(rs.getString(2));
            txtApellidoM.setText(rs.getString(3));
            txtSuperDni.setText(rs.getString(4));
            txtDireccion.setText(rs.getString(5));
            txtSueldo.setText(rs.getString(6));
            txtSexo.setText(rs.getString(7));
            txtDepartamento.setText(rs.getString(8));
            txtSubNombre.setText(rs.getString(9));
            txtSubSexo.setText(rs.getString(10));
            txtSubFechaNac.setText(rs.getString(11));
            txtSubRelacion.setText(rs.getString(12));
            txtFechaNac.setText(rs.getString(13));
            
            
            
            RdBtnMujer.setVisible(false);
            RdBtnHombre.setVisible(false);
            CmbSubRelacion.setVisible(false);
            BtnModificar.setVisible(true);
            btnBuscar.setEnabled(false);
            
            txtNombre.setEnabled(true);
            txtApellidoP.setEnabled(true);
            txtApellidoM.setEnabled(true);
            txtSuperDni.setEnabled(true);
            txtDireccion.setEnabled(true);
            txtSueldo.setEnabled(true);
            txtDepartamento.setEnabled(true);
            txtSexo.setEnabled(true);
            txtSubSexo.setEnabled(true);
            txtSubNombre.setEnabled(true);
            txtSubRelacion.setEnabled(true);
            txtFechaNac.setEnabled(true);
            txtSubFechaNac.setEnabled(true);
            
            txtDni.setEnabled(false);
            
            txtNombre.setEditable(false);
            txtApellidoP.setEditable(false);
            txtApellidoM.setEditable(false);
            txtSuperDni.setEditable(false);
            txtDireccion.setEditable(false);
            txtSueldo.setEditable(false);
            txtDepartamento.setEditable(false);
            txtSexo.setEditable(false);
            txtSubSexo.setEditable(false);
            txtSubNombre.setEditable(false);
            txtSubRelacion.setEditable(false);
            txtFechaNac.setEditable(false);
            txtSubFechaNac.setEditable(false);
           
            }else {
                JOptionPane.showMessageDialog(rootPane, "No se ha encontrado ningún empleado con ese Dni");
                int r=JOptionPane.showConfirmDialog(rootPane, "Desea agregar un nuevo empleado?");
                if(r==0){
                    PlaceHolder holder = new PlaceHolder(txtFechaNac, "1998-08-25");
            txtNombre.setEnabled(true);
            txtApellidoP.setEnabled(true);
            txtApellidoM.setEnabled(true);
            txtSuperDni.setEnabled(true);
            txtDireccion.setEnabled(true);
            txtSueldo.setEnabled(true);
            txtDepartamento.setEnabled(true);
            txtSexo.setEnabled(true);
            
            txtFechaNac.setEnabled(true);
        
            BtnAgregar.setVisible(true);
            
            CmbDepartamento.setVisible(true);
        CmbSubRelacion.setVisible(true);
        txtDepartamento.setVisible(false);
        txtSubRelacion.setVisible(false);
                 
            }
            }
            
        }
         catch (SQLException ex) {
            setTitle(ex.toString());
            
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void CmbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbDepartamentoActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_CmbDepartamentoActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
        
        CmbDepartamento.setVisible(true);
        CmbSubRelacion.setVisible(true);
        txtDepartamento.setVisible(false);
        txtSubRelacion.setVisible(false);
        BtnGuardar.setVisible(true);
        BtnEliminar.setVisible(true);
      
        txtSubFechaNac.setVisible(false);
        
        BtnModificar.setEnabled(false);
        
        txtNombre.setEditable(true);
        txtApellidoP.setEditable(true);
            txtApellidoM.setEditable(true);
            txtSuperDni.setEditable(true);
            txtDireccion.setEditable(true);
            txtSueldo.setEditable(true);
            txtDepartamento.setEditable(true);
            txtSexo.setEditable(true);
            txtSubSexo.setEditable(true);
            txtSubNombre.setEditable(true);
            txtSubRelacion.setEditable(true);
            txtFechaNac.setEditable(true);
            txtSubFechaNac.setEditable(true);
           

        txtSubSexo.setEditable(true);
        txtSubNombre.setEditable(true);
        txtSubRelacion.setEditable(true);
        txtFechaNac.setEditable(true);
        txtSubFechaNac.setEditable(true);
        
        
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
        try{
        Connection link=DriverManager.getConnection("jdbc:mysql://localhost/DB41", "root", "12503970");
        Statement comando = link.createStatement();
        String dato3;
        dato3=this.txtDni.getText();
        int r=JOptionPane.showConfirmDialog(rootPane, "Desea eliminar el registro?");
        if(r==0){
        comando.executeUpdate("DELETE * FROM empleado WHERE Dni='"+dato3+"';");
        JOptionPane.showMessageDialog(rootPane, "Se ha eliminado correctamente");
       txtDni.setText(null);
       txtDni.setEnabled(true);
       txtDni.setEditable(true);
       txtNombre.setText(null);
       txtNombre.setEnabled(false);
       txtApellidoP.setEnabled(false);
       txtApellidoP.setText(null);
       txtApellidoM.setText(null);
       txtDepartamento.setText(null);
       txtSueldo.setText(null);
       
        }
       
    }catch(SQLException ex){
        setTitle(ex.toString());
        
    }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
        try{
        Connection link=DriverManager.getConnection("jdbc:mysql://localhost/DB41", "root", "12503970");
        Statement comando = link.createStatement();
        String dato3, dato1, dato2;
        dato1=(String) CmbSubRelacion.getSelectedItem();
        dato2=(String) CmbDepartamento.getSelectedItem();
        dato3=this.txtDni.getText();
        comando.executeUpdate("UPDATE empleado SET Nombre='"+txtNombre.getText()+"', Apellido1='"+txtApellidoP.getText()+"', Apellido2='"+txtApellidoM.getText()+"', Sexo='"+txtSexo.getText()+"',Direccion='"+txtDireccion.getText()+"', SuperDni='"+txtSuperDni.getText()+"',Sueldo='"+txtSueldo.getText()+"' WHERE Dni='"+dato3+"';");
        JOptionPane.showMessageDialog(null, "Empleado modificado exitosamente "
                    , "Mensaje de bienvenida",
                    JOptionPane.INFORMATION_MESSAGE);
       txtDni.setText(null);
       txtDni.setEnabled(true);
       txtDni.setEditable(true);
       txtNombre.setText(null);
       txtNombre.setEnabled(false);
       txtApellidoP.setEnabled(false);
       txtApellidoP.setText(null);
       txtApellidoM.setText(null);
       txtDepartamento.setText(null);
       txtSueldo.setText(null);
       txtSuperDni.setText(null);
       txtDireccion.setText(null);
       txtFechaNac.setText(null);
       txtSubNombre.setText(null);
       txtSubFechaNac.setText(null);
       txtSuperDni.setEnabled(false);
        txtNombre.setEnabled(false);
        txtApellidoP.setEnabled(false);
        txtApellidoM.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtFechaNac.setEnabled(false);
        txtSubNombre.setEnabled(false);
        txtSubFechaNac.setEnabled(false);
        RdBtnMujer.setEnabled(false);
        RdBtnHombre.setEnabled(false);
        txtSubFechaNac.setEnabled(false);
        txtSueldo.setEnabled(false);
       
       
       
      
       
    }catch(SQLException ex){
        setTitle(ex.toString());
        JOptionPane.showMessageDialog(null, "No se pudo modifica el empleado"
                    , "Mensaje de error",
                    JOptionPane.ERROR);
        
    }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void txtFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int r=JOptionPane.showConfirmDialog(rootPane, "Desea salir?");
                if(r==0){ 
        Inicio p =new Inicio();
        p.setVisible(true);
        this.setVisible(false);
                }
                
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadosP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadosP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadosP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadosP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadosP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JComboBox<String> CmbDepartamento;
    private javax.swing.JComboBox<String> CmbSubRelacion;
    private javax.swing.JRadioButton RdBtnHombre;
    private javax.swing.JRadioButton RdBtnMujer;
    private javax.swing.JRadioButton RdBtnSubHombre;
    private javax.swing.JRadioButton RdBtnSubMujer;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtDireccion;
    public static javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtSubFechaNac;
    private javax.swing.JTextField txtSubNombre;
    private javax.swing.JTextField txtSubRelacion;
    private javax.swing.JTextField txtSubSexo;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtSuperDni;
    // End of variables declaration//GEN-END:variables
}
