/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import metodos.conectar;

/**
 *
 * @author Karenrgast
 */
public class ProyectoP extends javax.swing.JFrame {

    /**
     * Creates new form ProyectoP
     */
    public ProyectoP() {
        initComponents();
       this.setLocationRelativeTo(null); 
        txtNombreP.setEnabled(false);
        CmbUbicacion.setEnabled(false);
        CmbDepartamento.setEnabled(false);
        txtNumDpto.setEnabled(false);
        BtnNuevo.setEnabled(false);
        BtnEliminar.setEnabled(false);
        BtnGuardar.setEnabled(false);
        BtnModificar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumP = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        txtNombreP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CmbUbicacion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CmbDepartamento = new javax.swing.JComboBox<>();
        BtnNuevo = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtNumDpto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 150, 117));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("Proyecto ");
        jLabel1.setToolTipText("");

        jLabel3.setText("Nombre del Proyecto");

        jLabel4.setText("Numero del Proyecto");

        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/buscar.png"))); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        jLabel5.setText("Ubicación");

        CmbUbicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Valencia", "Sevilla", "Madrid", "Gijón" }));

        jLabel6.setText("Nombre del departamento");

        CmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Investigación", "Administración", "Sede Central" }));

        BtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Agregar.png"))); // NOI18N
        BtnNuevo.setText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        BtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/modificar.png"))); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/eliminar.png"))); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/guardar.png"))); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/back_arrow_14447.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmbUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(177, 177, 177))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNumP, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnBuscar))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumDpto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNumP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBuscar))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CmbUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumDpto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(BtnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        Connection link;
        
        try {
            link = DriverManager.getConnection("jdbc:mysql://localhost/DB41", "root", "12503970");
            Statement comando = link.createStatement();
            conectar c=new conectar();
            String dato;
            dato=this.txtNumP.getText();
            
            ResultSet rs=comando.executeQuery("SELECT  NombreProyecto, UbicacionProyecto, departamento.NombreDpto, NumeroDptoProyecto "
                    + "FROM proyecto "
                    + "INNER JOIN departamento ON proyecto.NumeroDptoProyecto=departamento.NumeroDpto "
                    + "WHERE proyecto.NumProyecto='"+dato+"';");
            
            if(rs.next()){
                
            txtNombreP.setText(rs.getString(1));
            CmbUbicacion.setSelectedItem(rs.getString(2));
            CmbDepartamento.setSelectedItem(rs.getString(3));
            txtNumDpto.setText(rs.getString(4));
            
            txtNombreP.setEnabled(true);
            CmbUbicacion.setEnabled(true);
            CmbDepartamento.setEnabled(true);
            
            BtnBuscar.setEnabled(false);
            txtNumDpto.setEnabled(true);
            txtNumP.setEnabled(false);
            txtNumDpto.setEditable(false);
            txtNombreP.setEditable(false);
            CmbUbicacion.setEditable(false);
            CmbDepartamento.setEditable(false);
            BtnModificar.setEnabled(true);
        
           
            }else {
                JOptionPane.showMessageDialog(rootPane, "No se ha encontrado ningún departamento con ése número ");
                int r=JOptionPane.showConfirmDialog(rootPane, "Desea agregar un nuevo proyecto?");
                if(r==0){
                BtnNuevo.setEnabled(true);
                txtNumP.setEnabled(true);
                txtNombreP.setEnabled(true);
                CmbUbicacion.setEnabled(true);
                CmbDepartamento.setEnabled(true);
                
                
                     }
            }
            
            
        }
         catch (SQLException ex) {
            setTitle(ex.toString());
            
        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        // TODO add your handling code here:
        BtnModificar.setEnabled(false);
        BtnBuscar.setEnabled(false);
        try{
        Connection link=DriverManager.getConnection("jdbc:mysql://localhost/DB41", "root", "12503970");
        Statement comando = link.createStatement();
        String dato3, dato1, dato2;
        dato1=(String) CmbUbicacion.getSelectedItem();
        dato2=(String) CmbDepartamento.getSelectedItem();
        dato3=this.txtNumP.getText();
        comando.executeUpdate("INSERT INTO proyecto VALUES('"+txtNumP.getText()+"','"+txtNombreP.getText()+"','"+dato1+"','"+txtNumDpto.getText()+"');");
        JOptionPane.showMessageDialog(null, "Proyecto regsitrado  exitosamente "
                    , "Mensaje de bienvenida",
                    JOptionPane.INFORMATION_MESSAGE);
       txtNumP.setText(null);
       txtNumP.setEnabled(true);
       txtNumP.setEditable(true);
       txtNombreP.setText(null);
       txtNombreP.setEnabled(false);
       CmbUbicacion.setEnabled(false);
       CmbDepartamento.setEnabled(false);
       txtNumDpto.setEnabled(false);

       
       txtNumDpto.setText(null);
       
      
       
       
       
       
       
      
       
    }catch(SQLException ex){
        setTitle(ex.toString());
        JOptionPane.showMessageDialog(null, "No se pudo registrar el proyecto "
                    , "Mensaje de error",
                    JOptionPane.ERROR);
        
    }
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
        txtNumP.setEnabled(false);
        txtNombreP.setEnabled(true);
        CmbUbicacion.setEnabled(true);
        CmbDepartamento.setEnabled(true);
        txtNombreP.setEditable(true);
        CmbUbicacion.setEditable(true);
        CmbDepartamento.setEditable(true);
        
        BtnBuscar.setEnabled(false);
        BtnEliminar.setEnabled(true);
        BtnGuardar.setEnabled(true);
        
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int r=JOptionPane.showConfirmDialog(rootPane, "Desea salir?");
                if(r==0){ 
        Inicio p =new Inicio();
        p.setVisible(true);
        this.setVisible(false);
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
        try{
        Connection link=DriverManager.getConnection("jdbc:mysql://localhost/DB41", "root", "12503970");
        Statement comando = link.createStatement();
        String dato3, dato1, dato2;
        dato1=(String) CmbUbicacion.getSelectedItem();
        dato3=this.txtNumP.getText();
        comando.executeUpdate("UPDATE proyecto SET NumProyecto="+txtNumP.getText()+ ", NombreProyecto='"+txtNombreP.getText()+"', UbicacionProyecto='"+dato1+"', NumeroDptoProyecto='"+txtNumDpto.getText()+"' WHERE NumProyecto='"+dato3+"';");
        JOptionPane.showMessageDialog(null, "Departamento modificado exitosamente "
                    , "Mensaje de bienvenida",
                    JOptionPane.INFORMATION_MESSAGE);
       txtNumP.setText(null);
       txtNumP.setEnabled(true);
       txtNumP.setEditable(true);
       txtNombreP.setText(null);
       txtNombreP.setEnabled(false);
       CmbUbicacion.setEnabled(false);
      CmbDepartamento.setEnabled(false);
      txtNumDpto.setEnabled(false);
      
       
               
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(rootPane, "No se pudo modificar");
        setTitle(ex.toString());
        
    }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
        try{
        Connection link=DriverManager.getConnection("jdbc:mysql://localhost/DB41", "root", "12503970");
        Statement comando = link.createStatement();
        String dato3;
        dato3=this.txtNumP.getText();
        int r=JOptionPane.showConfirmDialog(rootPane, "Desea eliminar el registro?");
        if(r==0){
        comando.executeUpdate("DELETE * FROM proyecto WHERE NumProyecto='"+dato3+"';");
        JOptionPane.showMessageDialog(rootPane, "Se ha eliminado correctamente");
       txtNumP.setText(null);
       txtNumP.setEnabled(true);
       
       txtNombreP.setText(null);
       txtNombreP.setEnabled(false);
       
       CmbUbicacion.setEnabled(true);
       CmbDepartamento.setEnabled(true);
 
        }
       
    }catch(SQLException ex){
        setTitle(ex.toString());
        JOptionPane.showMessageDialog(rootPane, "No se ha podido eliminar");
        
    }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JComboBox<String> CmbDepartamento;
    private javax.swing.JComboBox<String> CmbUbicacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtNumDpto;
    private javax.swing.JTextField txtNumP;
    // End of variables declaration//GEN-END:variables
}
